// V180000 OMNISCIENCE + F&O MICROSTRUCTURE GATE. No execution.
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const n=(v,d)=>Number.isFinite(Number(v))?Number(v):d;
function fnoScore(d={}){
 const f=d.futures||{},o=d.options||{},p=d.participant||{};const vals=[];
 if(Number.isFinite(Number(f.oiChangePct))&&Number.isFinite(Number(f.basisPct))) vals.push(clamp((Number(f.oiChangePct)>0?1:-1)*Math.min(Math.abs(Number(f.oiChangePct))/10,1)*.6+clamp(Number(f.basisPct)/1.5,-1,1)*.4,-1,1));
 if(Number.isFinite(Number(o.pcr))) vals.push(clamp((Number(o.pcr)-1)*1.8,-1,1));
 if(Number.isFinite(Number(o.ivSkewPct))) vals.push(clamp(-Number(o.ivSkewPct)/10,-1,1));
 if(Number.isFinite(Number(o.putOIChange))&&Number.isFinite(Number(o.callOIChange))) vals.push(clamp((Number(o.putOIChange)-Number(o.callOIChange))/Math.max(Math.abs(Number(o.putOIChange))+Math.abs(Number(o.callOIChange)),1),-1,1));
 if(Number.isFinite(Number(o.bidAskImbalance))) vals.push(clamp(Number(o.bidAskImbalance)/100,-1,1));
 if(Number.isFinite(Number(p.fiiIndexLong))&&Number.isFinite(Number(p.fiiIndexShort))) vals.push(clamp((Number(p.fiiIndexLong)-Number(p.fiiIndexShort))/Math.max(Math.abs(Number(p.fiiIndexLong))+Math.abs(Number(p.fiiIndexShort)),1),-1,1));
 const b=vals.length?vals.reduce((a,x)=>a+x,0)/vals.length:0;const agree=vals.length?Math.round(Math.max(vals.filter(x=>x>0).length,vals.filter(x=>x<0).length)/vals.length*100):0;return {bias:b,edge:clamp(Math.round(50+b*35),5,95),agreement:agree,signalsUsed:vals.length,complete:vals.length>=4};
}
exports.handler=async(event)=>{try{const body=event.body?JSON.parse(event.body):{};const base=n(body.edge,50),agree=n(body.agreement,0),unc=n(body.uncertainty,100),risk=n(body.risk,100),integrity=n(body.integrity,80),robust=n(body.robustness,80);const fs=fnoScore(body.derivatives||{});const dataMode=fs.signalsUsed? 'DERIVATIVES_PARTIAL':'SPOT_ONLY';const fused=fs.signalsUsed?clamp(Math.round(base*.55+fs.edge*.45),5,95):base;const fnoAgreement=fs.signalsUsed?fs.agreement:0;const finalAgreement=fs.signalsUsed?Math.round(agree*.65+fnoAgreement*.35):agree;const finalIntegrity=clamp(Math.round(integrity-(fs.signalsUsed<4?10:0)),0,100);const finalRobust=clamp(Math.round(robust-(fs.signalsUsed<4?8:0)),0,100);const gate=finalAgreement>=75&&finalIntegrity>=72&&finalRobust>=72&&unc<=35&&risk<=40&&(!fs.signalsUsed||fs.complete);const action=gate?(fused>=68?'BUY':fused<=32?'SELL':'WAIT'):'WAIT';const oracleScore=clamp(Math.round(.25*finalIntegrity+.25*finalRobust+.2*finalAgreement+.15*(100-unc)+.15*(100-risk)),0,100);return {statusCode:200,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*'},body:JSON.stringify({version:'V180000',action,gate:gate?'PASS':'ABSTAIN',edge:fused,integrity:finalIntegrity,robustness:finalRobust,oracleScore,dataMode,derivativeEvidence:{complete:fs.complete?100:Math.round(fs.signalsUsed/6*100),signalsUsed:fs.signalsUsed,fnoEdge:fs.edge,fnoAgreement:fs.agreement},reason:gate?'Independent spot and derivatives evidence survived the quality/risk gates.':'Insufficient or conflicting evidence; WAIT is enforced until stronger evidence is available.'})};}catch(e){return {statusCode:400,headers:{'content-type':'application/json'},body:JSON.stringify({action:'NO-TRADE',gate:'ABSTAIN',error:e.message})}}};
